# функція для сповіщення git actions
actions_status:
  if: ${{ failure() }}
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Send Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,event
      id: slack