version: "3.9"

networks:
  bot_network:
    name: hpkchatbot_network

services:
  bot:
    build: .
    env_file:
      app/.env
    environment:
      - TZ=Europe/Kiev
      - DB_HOST=mariadb
      - REDIS_HOST=redis
    volumes:
      - ./data:/bot/data
      - ./logs:/bot/logs
    networks:
      - bot_network
    depends_on:
      - mariadb
      - redis

  mariadb:
    image:
      "mariadb:10.6"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - bot_network

  redis:
    image:
      "redis:7.0-alpine"
    command:
      redis-server --appendonly yes --replica-read-only no
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - bot_network


  phpmyadmin:
    image:
      "phpmyadmin:latest"
    ports:
      - "0.0.0.0:8080:80"
    environment:
      - PMA_HOST=mariadb
    networks:
      - bot_network

