- name: install main 
  hosts: "servers"
  become: true # install by super user
  tasks:

    - name: Install docker.io
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: true
      with_items:
        - "docker.io"
