---
- name: Install main files
  hosts: "servers"
  become: true # install by super user
  tasks:

    - name: Install nginx, docker.io, git, vim, net-tools
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: true
      with_items:
        - "docker.io"
