

- name: Install docker.io
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: true
  with_items:
    - "docker.io"
    - "docker"
    - "python3"
    - "python3-pip"

- name: Install docker in python
  ansible.builtin.pip:
    name: docker, docker-compose
    executable: pip3
