- name: Create path
  ansible.builtin.file:
    path: /bot
    owner: git
    group: git
    mode: '0755'
    state: directory

- name: Copy .env
  ansible.builtin.copy:
    content:
      "
      API_TOKEN={{ API_TOKEN }}\n
      WEATHER_TOKEN={{ WEATHER_TOKEN }}\n
      ID_GROUP_ADMIN={{ ID_GROUP_ADMIN }}\n
      DB_NAME={{ DB_NAME }}\n
      DB_USER={{ DB_USER }}\n
      DB_PASSWORD={{ DB_PASSWORD }}\n
      "
    dest: /bot/.env
    owner: git
    group: git

#- name: Create path for redis.conf
#  ansible.builtin.file:
#    path: /bot/redis/conf
#    mode: '0755'
#    state: directory
#
#- name: Create redis conf
#  ansible.builtin.copy:
#    content:
#      "slave-read-only no"
#    dest: /bot/redis/conf/redis.conf

- name: Login in DockerHub
  community.docker.docker_login:
    username: "{{ docker_hub_login }}"
    password: "{{ docker_hub_pass }}"

- name: Update project
  community.docker.docker_compose:
    project_name: hpkchatbot
    pull: true
    definition:
      version: "3.9"
      networks:
        net_bot:
          name: net_bot
      services:
        bot:
          image:
            textadi/hpkchatbot:latest
          env_file:
            /bot/.env
          environment:
            - DB_HOST=mariadb
            - REDIS_HOST=redis
            - TZ=Europe/Kiev
          volumes:
            - /bot/data:/bot/data
            - /bot/logs:/bot/logs
          networks:
            - net_bot
          depends_on:
            - mariadb
            - redis

        mariadb:
          image:
            mariadb:10.6
          ports:
            - 127.0.0.1:3306:3306
          volumes:
            - /bot/db:/var/lib/mysql
          networks:
            - net_bot
          environment:
            - MYSQL_ROOT_PASSWORD=yes
            - MYSQL_USER={{ DB_USER }}
            - MYSQL_PASSWORD={{ DB_PASSWORD }}
            - MYSQL_DATABASE={{ DB_NAME }}
        redis:
          image:
            redis:7.0-alpine
          command:
            redis-server --appendonly yes --replica-read-only no
          volumes:
            - /bot/redis/data:/data
          networks:
            - net_bot

- name: Log out of DockerHub
  community.docker.docker_login:
    state: absent

#- name: Fix redis cache
#  ansible.builtin.shell:
#    cmd:
#      echo slaveof no one | nc 127.0.0.1 6379 -q 1
