name: Github CI/CD

on:
  push:
    branches: "main"

env:
  DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login in DockerHub
      run: docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS docker.io

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $DOCKER_HUB_LOGIN/$DOCKER_HUB_REPO:latest
        docker build . --file Dockerfile --tag $DOCKER_HUB_LOGIN/$DOCKER_HUB_REPO:$(date +'%Y-%m-%d')          

    - name: Push the Docker image
      run: |
        docker push $DOCKER_HUB_LOGIN/$DOCKER_HUB_REPO:latest
        docker push $DOCKER_HUB_LOGIN/$DOCKER_HUB_REPO:$(date +'%Y-%m-%d') 

  update:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run playbook
        uses:  arillso/action.playbook@master
        with:
          playbook: ansible/init.yml
          inventory: ansible/hosts.ini
          user: root
          become: true
          private_key: ${{ secrets.PRIVATE_KEY }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'

          
